apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: jupyter-test
spec:
  scalePVC:
    threshold: 50  # percentage
    scaleFactor: 2
    maxCapacity: 4Gi
  template:
    spec:
      volumes:
        - name: test-vol
          persistentVolumeClaim:
            claimName: test-pvc
        - emptyDir:
            medium: Memory
          name: dshm
      containers:
      - image: gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu:v1.0.0
        name: notebook
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - mountPath: /home/jovyan
            name: test-vol
          - mountPath: /dev/shm
            name: dshm
      
